name: Radar de Imóveis

on:
  workflow_dispatch:

jobs:
  buscar-imoveis:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          pip install requests beautifulsoup4

      - name: Executar radar
        env:
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
        run: python radar.py
